name: Node.js CI

on:
  push:
    branches:  [master]
  pull_request:
    branches:  [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: [16.x, 18.x]
        java-version: [ '17' ]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3
      - name: Use microsoft Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: ${{ matrix.java-version }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run lint:check
      - run: npm audit --audit-level=critical
      - run: npm run test:ci
      - run: npm run build
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
